@ParametersAreNonnullByDefault

@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault

package com.hexagram2021.emeraldcraftextra;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;